---
- name: has already installed composer
  stat: path=/usr/local/bin/composer
  register: composer_already
  always_run: yes
  tags:
    - symfony2:composer

- name: composer install
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && mv composer.phar /usr/local/bin/composer && chmod 0755 /usr/local/bin/composer
  when: composer_already.stat.exists != True
  tags:
    - symfony2:composer
